### ISSUE TITLE
Assets loaded in content script result in 404

### ISSUE THREAD

**Issue by hdodov** [crxjs/chrome-extension-tools#842]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

I have a simple content script that imports CSS with fonts:

manifest.json:
```json
{
	"content_scripts": [
		{
			"js": ["src/content.tsx"],
			"matches": ["file:///*", "http://*/*", "https://*/*"]
		}
	]
}
```

content.tsx:
```ts
import "./index.css";
// Other stuff...
```

index.css:
```css
@import "@fontsource/inter/400.css";
/* Other stuff... */
```

I do the same in the extension popup and it works perfectly there. However, in the content script, it results in the extension attempting to load the resources from the visited website, and you obviously get a 404:

```
https://example.com/assets/inter-latin-400-normal-2301bb03.woff2 → 404
```

This problem has been raised in Stack Overflow and [the solution](https://stackoverflow.com/a/4536058/3130281) is to use a special string in the CSS resource path, as [explained in the Chrome docs](https://developer.chrome.com/docs/extensions/reference/api/i18n#overview-predefined):

```css
body {
	background-image: url('chrome-extension://__MSG_@@extension_id__/background.png');
}
```

And indeed, if I build my extension, go to the generated CSS, and manually prepend `chrome-extension://__MSG_@@extension_id__`, everything starts working. In other words, this:

```css
@font-face {
	src: url(/assets/inter-latin-400-normal-2301bb03.woff2) format("woff2");
}
```

…has to turn to this:

```css
@font-face {
	src: url(chrome-extension://__MSG_@@extension_id__/assets/inter-latin-400-normal-2301bb03.woff2) format("woff2");
}
```

### Reproduction

Create a content script and try to import any CSS asset.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 6.68 GB / 15.82 GB
  Binaries:
    Node: 20.10.0 - ~\AppData\Local\Volta\tools\image\node\20.10.0\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 10.2.3 - ~\AppData\Local\Volta\tools\image\node\20.10.0\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @crxjs/vite-plugin: ^2.0.0-beta.21 => 2.0.0-beta.21 
    vite: ^4.3.9 => 4.5.0 
```
```


### Severity

annoyance
